name: telegram_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore : ^4.15.4
  image: ^4.1.6
  animator: ^3.3.0
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1
  timeago: ^3.6.1
  firebase_auth: ^4.17.4
  geolocator: ^10.1.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.6.5
  fluttertoast: ^8.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^2.23.0
  cached_network_image: ^3.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google.png

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf

