// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnE-mMDqs-Q8NGrwE2Se1J7PfgTPUiiis',
    appId: '1:941210601874:web:bdc01a54db760a13fc994b',
    messagingSenderId: '941210601874',
    projectId: 'social-telegram-chat-app',
    authDomain: 'social-telegram-chat-app.firebaseapp.com',
    storageBucket: 'social-telegram-chat-app.appspot.com',
    measurementId: 'G-MK3G20B5H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcm5yNHczhMrUIUpcSSOpoHSWnB9edjyo',
    appId: '1:941210601874:android:3219e4b7c1c38ac6fc994b',
    messagingSenderId: '941210601874',
    projectId: 'social-telegram-chat-app',
    storageBucket: 'social-telegram-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-fNNUMjLbhmzY2-m_gzhc9kjMii4L9A4',
    appId: '1:941210601874:ios:c1c743bed17b249efc994b',
    messagingSenderId: '941210601874',
    projectId: 'social-telegram-chat-app',
    storageBucket: 'social-telegram-chat-app.appspot.com',
    iosBundleId: 'com.example.telegramChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-fNNUMjLbhmzY2-m_gzhc9kjMii4L9A4',
    appId: '1:941210601874:ios:44c205a7e38823a8fc994b',
    messagingSenderId: '941210601874',
    projectId: 'social-telegram-chat-app',
    storageBucket: 'social-telegram-chat-app.appspot.com',
    iosBundleId: 'com.example.telegramChat.RunnerTests',
  );
}
