// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA557Buw6yjl1c70Cn5MNJ2ch1V9TQ1SbM',
    appId: '1:843393508821:web:5baba137763261c6f7c95c',
    messagingSenderId: '843393508821',
    projectId: 'telegram-chat-32e98',
    authDomain: 'telegram-chat-32e98.firebaseapp.com',
    databaseURL: 'https://telegram-chat-32e98-default-rtdb.firebaseio.com',
    storageBucket: 'telegram-chat-32e98.appspot.com',
    measurementId: 'G-ZZBJJENSXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OjZ7CqfmXTTbP22fjTC0RlKpyXLj1XE',
    appId: '1:843393508821:android:251498a1eb898b7af7c95c',
    messagingSenderId: '843393508821',
    projectId: 'telegram-chat-32e98',
    databaseURL: 'https://telegram-chat-32e98-default-rtdb.firebaseio.com',
    storageBucket: 'telegram-chat-32e98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYosrdnBed5IjwjJh4Cd5dgfB-8vNmvDU',
    appId: '1:843393508821:ios:8500e8fc7410b2a9f7c95c',
    messagingSenderId: '843393508821',
    projectId: 'telegram-chat-32e98',
    databaseURL: 'https://telegram-chat-32e98-default-rtdb.firebaseio.com',
    storageBucket: 'telegram-chat-32e98.appspot.com',
    androidClientId: '843393508821-8q2h2nhf2r4kbqfttiidm57ricbfpuga.apps.googleusercontent.com',
    iosClientId: '843393508821-590pjgcq6gsbt7b0ql3c9j6n9r3umd2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.telegramChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYosrdnBed5IjwjJh4Cd5dgfB-8vNmvDU',
    appId: '1:843393508821:ios:c8d77871168cdf66f7c95c',
    messagingSenderId: '843393508821',
    projectId: 'telegram-chat-32e98',
    databaseURL: 'https://telegram-chat-32e98-default-rtdb.firebaseio.com',
    storageBucket: 'telegram-chat-32e98.appspot.com',
    androidClientId: '843393508821-8q2h2nhf2r4kbqfttiidm57ricbfpuga.apps.googleusercontent.com',
    iosClientId: '843393508821-rk0os28kkd22qhcgbkf2ri66s3298k3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.telegramChat.RunnerTests',
  );
}
